### PR TITLE
Video resolution changed  many times

### PR DESCRIPTION
**Pull request by thegobot**
If frame.additionalInfo.video.width == 0 this does not mean changing the resolution

```
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 640 //is keyFrame
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 640 //is keyFrame
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 640 //is keyFrame
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 640 //is keyFrame
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 0
frame.additionalInfo.video.width == 640 //is keyFrame
...
```

Why is the width zero? I am using the latest build

### CODE REVIEW

**Comment by daijh** [comment]
Mixed stream is fixed resolution.   
Is it forward stream av stream output?
How can we reproduce this issue?

**Comment by daijh** [comment]
@ChenLi please have a check the VideoFrameConstructor

**Comment by daijh** [comment]
Why VideoFrameConstructor sent a VideoFrame with resolution 0x0?
0x0 is not a valid resolution.

**Comment by daijh** [comment]
Understood to add some guard code in AVStreamOut is able to simply fix this issue.

But every parameter should provide a meaningful value (VideoFrameConstructor), then we can expect definite behavior on that parameter (AVStreamOut).

The exact meaning of VideoFrame.width = 0  and VideoFrame.height = 0 from VideoFrameConstructor is not clear here.
- If it means error frame, it can be dropped directly by VideoFrameConstructor, instead of sending to AVStreamOut
- If it means VideoSize not changed, VideoFrameConstructor can set previous video size instead of 0x0
- If it means b-frame, we can add additional "frame type" field. BTW, b-frame can get valid video size from the sps/pps

I suggest to figure out the exact meaning of VideoFrame size 0x0, before provide a fix.

**Comment by starwarfan** [comment]
#604 update the logic in VideoFrameConstructor

**Pull request closed without merging**
